// <auto-generated />
namespace BusBookingSystem.Domain.EF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class dbstructurechanged : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dbstructurechanged));
        
        string IMigrationMetadata.Id
        {
            get { return "201704131401007_dbstructurechanged"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
